- name: conditions to write less than or greater than10
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter number
    private: false
    # vars:
  #   my_number: 139 # number

  tasks:

   - name: print this if number less than 10
     ansible.builtin.debug:
       msg: "Given number {{ my_number }} is less than 10"
     when: my_number | int < 10 # conditional expression

   - name: print this if number greater than equal to 10
     ansible.builtin.debug:
       msg: "Given number {{ my_number }} is greater than equal to  10"
     when: my_number | int >= 10 # conditional expression
